[package]
name = "coda-supervisor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.23"
coda-ipc = { version = "0.1.0", path = "../coda-ipc" }
